const monthNames = ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
const arabicDigits = value => String(value).replace(/\d/g, digit => '٠١٢٣٤٥٦٧٨٩'[digit]);
const money = value => `${arabicDigits(Math.round(value).toLocaleString('en-US'))} دج`;
const monthKey = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2,'0')}`;
let selectedMonth = new Date();
let state = JSON.parse(localStorage.getItem('workshopData') || 'null') || { workers: [], diggers: [], trucks: [], entries: [] };
const defaults = { workers: [['العامل ١',1800],['العامل ٢',1800],['العامل ٣',1800],['العامل ٤',1800],['العامل ٥',1800],['العامل ٦',1800]], diggers: [['حفّار ١',350],['حفّار ٢',350],['حفّار ٣',350],['حفّار ٤',350]], trucks: [['الشاحنة ٠١','شاحنة'],['الشاحنة ٠٢','شاحنة']] };
Object.keys(defaults).forEach(type => { if (!state[type].length) state[type] = defaults[type].map(([name, rate]) => ({ id: crypto.randomUUID(), name, rate })); });
state.workers.forEach(worker => Object.assign(worker, { monthlySalary: Number(worker.monthlySalary) || 0, workDays: Number(worker.workDays) || 0, overtimeHours: Number(worker.overtimeHours) || 0, overtimeRate: Number(worker.overtimeRate) || 0, advance: Number(worker.advance) || 0 }));
const save = () => localStorage.setItem('workshopData', JSON.stringify(state));
const getConfig = () => JSON.parse(localStorage.getItem('supabaseConfig') || 'null');
async function supabaseRequest(table, method, body){ const config=getConfig(); if(!config?.url || !config?.key) return; const response=await fetch(`${config.url}/rest/v1/${table}`, {method, headers:{apikey:config.key, Authorization:`Bearer ${config.key}`, 'Content-Type':'application/json', Prefer:'resolution=merge-duplicates'}, body:JSON.stringify(body)}); if(!response.ok) throw new Error(`Supabase ${response.status}`); }
async function supabaseFetch(table){ const config=getConfig(); const response=await fetch(`${config.url}/rest/v1/${table}?select=*`, {headers:{apikey:config.key, Authorization:`Bearer ${config.key}`}}); if(!response.ok) throw new Error(`Supabase ${response.status}`); return response.json(); }
async function loadFromSupabase(){ const config=getConfig(); if(!config?.url || !config?.key) return; try { const [workers,diggers,trucks,workerEntries,diggerEntries,truckEntries]=await Promise.all([supabaseFetch('workers'),supabaseFetch('diggers'),supabaseFetch('trucks'),supabaseFetch('worker_entries'),supabaseFetch('digger_entries'),supabaseFetch('truck_entries')]); if(workers.length)state.workers=workers.map(row=>({id:row.id,name:row.name,rate:Number(row.daily_rate),monthlySalary:Number(row.monthly_salary)||0,workDays:Number(row.work_days)||0,overtimeHours:Number(row.overtime_hours)||0,overtimeRate:Number(row.overtime_rate)||0,advance:Number(row.advance)||0})); if(diggers.length)state.diggers=diggers.map(row=>({id:row.id,name:row.name,rate:Number(row.hourly_rate)})); if(trucks.length)state.trucks=trucks.map(row=>({id:row.id,name:row.name,rate:'شاحنة'})); state.entries=[...workerEntries.map(row=>({id:row.id,type:'workers',personId:row.worker_id,date:row.entry_date,month:row.entry_date.slice(0,7),amount:Number(row.days)})),...diggerEntries.map(row=>({id:row.id,type:'diggers',personId:row.digger_id,date:row.entry_date,month:row.entry_date.slice(0,7),amount:Number(row.hours)})),...truckEntries.map(row=>({id:row.id,type:'trucks',personId:row.truck_id,date:row.entry_date,month:row.entry_date.slice(0,7),amount:Number(row.loads)}))]; state.workers.forEach(worker=>{if(!worker.workDays)worker.workDays=entriesFor('workers',worker.id).reduce((sum,entry)=>sum+Number(entry.amount),0);}); qs('#syncLabel').textContent='متصل بـ Supabase'; } catch(error){ qs('#syncLabel').textContent='تعذر الاتصال، محليًا'; console.warn(error); } }
async function syncToSupabase(){ const config=getConfig(); if(!config?.url || !config?.key) return; try { await Promise.all([supabaseRequest('workers','POST',state.workers.map(({id,name,rate,monthlySalary,workDays,overtimeHours,overtimeRate,advance})=>({id,name,daily_rate:rate,monthly_salary:monthlySalary,work_days:workDays,overtime_hours:overtimeHours,overtime_rate:overtimeRate,advance}))), supabaseRequest('diggers','POST',state.diggers.map(({id,name,rate})=>({id,name,hourly_rate:rate}))), supabaseRequest('trucks','POST',state.trucks.map(({id,name})=>({id,name})))]); const grouped={workers:[],diggers:[],trucks:[]}; state.entries.forEach(entry=>{ const row={id:entry.id,entry_date:entry.date}; if(entry.type==='workers')grouped.workers.push({...row,worker_id:entry.personId,days:entry.amount}); if(entry.type==='diggers')grouped.diggers.push({...row,digger_id:entry.personId,hours:entry.amount}); if(entry.type==='trucks')grouped.trucks.push({...row,truck_id:entry.personId,loads:entry.amount}); }); await Promise.all([supabaseRequest('worker_entries','POST',grouped.workers),supabaseRequest('digger_entries','POST',grouped.diggers),supabaseRequest('truck_entries','POST',grouped.trucks)]); qs('#syncLabel').textContent='متصل بـ Supabase'; } catch(error){ qs('#syncLabel').textContent='تعذر الاتصال، محليًا'; console.warn(error); } }
const currentMonthKey = () => monthKey(selectedMonth);
const currentMonthLabel = () => `${monthNames[selectedMonth.getMonth()]} ${arabicDigits(selectedMonth.getFullYear())}`;
const qs = selector => document.querySelector(selector);
function showToast(message){ const toast=qs('#toast'); toast.textContent=message; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),2400); }
function renderMonths(){ qs('#dashboardMonth').textContent=currentMonthLabel(); document.querySelectorAll('.current-month').forEach(el=>el.textContent=currentMonthLabel()); qs('#workersCount').textContent=arabicDigits(state.workers.length); qs('#trucksCount').textContent=arabicDigits(state.trucks.length); }
function entriesFor(type, id){ return state.entries.filter(entry => entry.type===type && entry.personId===id && entry.month===currentMonthKey()); }
function renderPeople(type){ const grid=qs(`#${type}Grid`); grid.innerHTML=''; state[type].forEach(person=>{ const entries=entriesFor(type,person.id); const amount=entries.reduce((sum,entry)=>sum+Number(entry.amount),0); const workDays=type==='workers'?Number(person.workDays)||0:amount; const total=type==='trucks'?amount:type==='workers'?(workDays*Number(person.rate))+(Number(person.overtimeHours)*Number(person.overtimeRate))-Number(person.advance):amount*Number(person.rate); const unit=type==='workers'?'يوم عمل':type==='diggers'?'ساعة':'شحنة'; const workerFields=type==='workers'?`<div class="worker-fields"><label>الراتب الشهري<input type="number" min="0" data-field="monthlySalary" data-id="${person.id}" value="${person.monthlySalary}"><small>دج</small></label><label>عدد أيام العمل<input type="number" min="0" step="0.5" data-field="workDays" data-id="${person.id}" value="${workDays}"><small>يوم</small></label><label>اليومية<input type="number" min="0" data-field="rate" data-id="${person.id}" value="${person.rate}"><small>دج</small></label><label>الساعات الإضافية<input type="number" min="0" step="0.5" data-field="overtimeHours" data-id="${person.id}" value="${person.overtimeHours}"><small>ساعة</small></label><label>ثمن الساعة<input type="number" min="0" data-field="overtimeRate" data-id="${person.id}" value="${person.overtimeRate}"><small>دج</small></label><label>التسبيقة<input type="number" min="0" data-field="advance" data-id="${person.id}" value="${person.advance}"><small>دج</small></label></div>`:''; const card=document.createElement('article'); card.className=`person-card ${type==='trucks'?'truck-card':''}`; card.innerHTML=`<div class="person-top"><div class="person-avatar">${person.name.slice(-2, -1) || 'م'}</div><div><input class="edit-name" data-id="${person.id}" value="${person.name}" aria-label="اسم ${person.name}"><span class="person-role">${type==='workers'?'عامل يومي':type==='diggers'?'أجر بالساعة':'متابعة الشحنات'}</span></div><button class="remove-person" data-remove-person="${type}" data-person="${person.id}" aria-label="حذف ${person.name}" title="حذف">×</button></div>${type!=='trucks'&&type!=='workers'?`<div class="rate"><span>الأجر بالساعة</span><input type="number" min="0" data-rate="${person.id}" value="${person.rate}"> <span>دج</span></div>`:''}${workerFields}<div class="total-row"><div><small>${arabicDigits(workDays)} ${unit} مسجل</small><strong>${type==='workers'?'الصافي: ':''}${money(total)}</strong></div><button data-open-entry="${type}" data-person="${person.id}">＋ إضافة</button></div>`; grid.appendChild(card); }); }
function addPerson(type){ const isTruck=type==='trucks'; const person={id:crypto.randomUUID(),name:isTruck?`الشاحنة ${arabicDigits(state.trucks.length+1)}`:`العامل ${arabicDigits(state.workers.length+1)}`,rate:isTruck?'شاحنة':1800,...(type==='workers'?{monthlySalary:0,workDays:0,overtimeHours:0,overtimeRate:0,advance:0}:{})}; state[type].push(person); render(); showToast(isTruck?'تمت إضافة شاحنة جديدة':'تمت إضافة عامل جديد'); }
function removePerson(type, id){ const person=state[type].find(item=>item.id===id); if(!person || !window.confirm(`هل تريد حذف ${person.name}؟`))return; state[type]=state[type].filter(item=>item.id!==id); state.entries=state.entries.filter(entry=>entry.personId!==id); render(); showToast('تم حذف العنصر'); }
function renderSummary(){ const totals={workers:0,diggers:0,trucks:0}, units={workers:0,diggers:0,trucks:0}; state.entries.filter(e=>e.month===currentMonthKey()).forEach(e=>{units[e.type]+=Number(e.amount); totals[e.type]+=e.type==='trucks'?Number(e.amount):Number(e.amount)*(Number(state[e.type].find(p=>p.id===e.personId)?.rate)||0);}); totals.workers=state.workers.reduce((sum,worker)=>sum+(Number(worker.workDays||0)*Number(worker.rate))+(Number(worker.overtimeHours)*Number(worker.overtimeRate))-Number(worker.advance),0); qs('#workerTotal').textContent=money(totals.workers); qs('#diggerTotal').textContent=money(totals.diggers); qs('#truckTotal').textContent=`${arabicDigits(units.trucks)} شحنة`; qs('#workerMeta').textContent=`${arabicDigits(state.workers.reduce((sum,worker)=>sum+Number(worker.workDays||0),0))} يوم حضور`; qs('#diggerMeta').textContent=`${arabicDigits(units.diggers)} ساعة عمل`; qs('#truckMeta').textContent=`${arabicDigits(units.trucks)} رحلة مسجلة`; const recent=state.entries.filter(e=>e.month===currentMonthKey()).slice(-5).reverse(); const list=qs('#activityList'); list.innerHTML=recent.length?recent.map(e=>{const person=state[e.type].find(p=>p.id===e.personId);return `<div class="activity-row"><span class="activity-dot"></span><div><strong>${person?.name||'سجل محذوف'}</strong><small>${e.type==='workers'?'حضور يومي':e.type==='diggers'?'ساعات حفر':'شحنات'} · ${e.date}</small></div><b>${arabicDigits(e.amount)} ${e.type==='diggers'?'ساعة':e.type==='trucks'?'شحنة':'يوم'}</b></div>`}).join(''):`<div class="empty-state"><span>✦</span><strong>لا توجد حركات بعد</strong><p>ابدأ بإضافة حضور أو ساعات أو شحنات لهذا الشهر.</p></div>`; }
function render(){ renderMonths(); ['workers','diggers','trucks'].forEach(renderPeople); renderSummary(); save(); syncToSupabase(); }
function openEntry(type='workers', personId=''){ qs('#entryModal').classList.add('open'); qs('#entryType').value=type; qs('#entryDate').value=new Date().toISOString().slice(0,10); const select=qs('#entryPerson'); select.innerHTML=state[type].map(p=>`<option value="${p.id}" ${p.id===personId?'selected':''}>${p.name}</option>`).join(''); updateEntryLabels(); }
function updateEntryLabels(){ const type=qs('#entryType').value; qs('#amountLabel').firstChild.textContent=type==='workers'?'عدد الأيام':type==='diggers'?'عدد الساعات':'عدد الشحنات'; qs('#amountLabel').querySelector('input').step=type==='workers'?'0.5':'1'; qs('#modalTitle').textContent=type==='workers'?'تسجيل حضور':type==='diggers'?'تسجيل ساعات':'تسجيل شحنات'; }
document.addEventListener('click', event=>{ const view=event.target.closest('[data-view]'); if(view){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view.dataset.view));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`${view.dataset.view}View`));qs('#pageLabel').textContent=view.dataset.view==='dashboard'?'لوحة المتابعة':view.dataset.view==='workers'?'العمال اليوميون':view.dataset.view==='diggers'?'عمال الحفر':'الشاحنات';qs('#sidebar').classList.remove('open');} const add=event.target.closest('[data-add-person]'); if(add) addPerson(add.dataset.addPerson); const remove=event.target.closest('[data-remove-person]'); if(remove) removePerson(remove.dataset.removePerson,remove.dataset.person); const entry=event.target.closest('[data-open-entry]'); if(entry) openEntry(entry.dataset.openEntry,entry.dataset.person||''); if(event.target.closest('[data-month]')){selectedMonth.setMonth(selectedMonth.getMonth()+(event.target.closest('[data-month]').dataset.month==='next'?1:-1));render();} if(event.target.closest('[data-close-modal]'))qs('#entryModal').classList.remove('open'); if(event.target.closest('[data-close-settings]'))qs('#settingsModal').classList.remove('open'); });
qs('#entryType').addEventListener('change',()=>{ const type=qs('#entryType').value; qs('#entryPerson').innerHTML=state[type].map(p=>`<option value="${p.id}">${p.name}</option>`).join('');updateEntryLabels(); });
qs('#entryForm').addEventListener('submit',event=>{event.preventDefault();const type=qs('#entryType').value;state.entries.push({id:crypto.randomUUID(),type,personId:qs('#entryPerson').value,date:qs('#entryDate').value,month:qs('#entryDate').value.slice(0,7),amount:Number(qs('#entryAmount').value)});qs('#entryModal').classList.remove('open');render();showToast('تم حفظ السجل بنجاح');});
document.addEventListener('change',event=>{if(event.target.matches('.edit-name,.rate input,[data-field]')){const type=event.target.closest('.person-card').classList.contains('truck-card')?'trucks':event.target.closest('#diggersGrid')?'diggers':'workers';const person=state[type].find(p=>p.id===event.target.dataset.id||p.id===event.target.dataset.rate);if(person){if(event.target.dataset.field)person[event.target.dataset.field]=Number(event.target.value);else if(event.target.dataset.rate)person.rate=Number(event.target.value);else person.name=event.target.value;render();showToast('تم تحديث البيانات');}}});
qs('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('darkMode',document.body.classList.contains('dark'));}); qs('#mobileMenu').addEventListener('click',()=>qs('#sidebar').classList.toggle('open')); qs('#quickAdd').addEventListener('click',()=>openEntry()); qs('#openSettings').addEventListener('click',()=>qs('#settingsModal').classList.add('open')); qs('#settingsForm').addEventListener('submit',event=>{event.preventDefault();localStorage.setItem('supabaseConfig',JSON.stringify({url:qs('#supabaseUrl').value,key:qs('#supabaseKey').value}));qs('#settingsModal').classList.remove('open');qs('#syncLabel').textContent=qs('#supabaseUrl').value?'اتصال Supabase محفوظ':'يُحفظ محليًا';showToast('تم حفظ إعدادات الاتصال');});
qs('#todayLabel').textContent=new Intl.DateTimeFormat('ar-DZ',{weekday:'long',day:'numeric',month:'long'}).format(new Date()); if(localStorage.getItem('darkMode')==='true')document.body.classList.add('dark'); const config=getConfig();if(config){qs('#supabaseUrl').value=config.url||'';qs('#supabaseKey').value=config.key||'';qs('#syncLabel').textContent='اتصال Supabase محفوظ';} (async()=>{await loadFromSupabase();render();})();
